@startuml
class ItemCasamentoMapperTest {
    + Setup() : void
    + WhenMappingEntityToModelItShouldHaveSameProperties() : void
    + WhenMappingModelToEntityItShouldHaveSameProperties() : void
}
@enduml
