@startuml
!include .\\noivaciaAPP\src\Calendario.puml
!include .\\noivaciaAPP\src\Menu.puml
!include .\\noivaciaAPP\src\Program.puml
!include .\\noivaciaAPP.Test\src\CalendarTest.puml
!include .\\noivaciaAPP.Test\src\ItemRepositoryTest.puml
!include .\\noivaciaAPP.Test\src\Novo.puml
!include .\\noivaciaAPP.Test\src\UnitTest1.puml
!include .\\noivaciaAPP.Test\stub\ItemCasamentoStub.puml
!include .\\noivaciaAPP\src\entity\Entity.puml
!include .\\noivaciaAPP\src\entity\ItemFestaEntity.puml
!include .\\noivaciaAPP\src\gerenciador\GerenciadorCasamento.puml
!include .\\noivaciaAPP\src\gerenciador\GerenciadorDeItem.puml
!include .\\noivaciaAPP\src\gerenciador\GerenciadorEspaco.puml
!include .\\noivaciaAPP\src\mapper\IMapper.puml
!include .\\noivaciaAPP\src\mapper\ItemCasamentoMapper.puml
!include .\\noivaciaAPP\src\model\Casamento.puml
!include .\\noivaciaAPP\src\model\Espaco.puml
!include .\\noivaciaAPP\src\model\EspacoBase.puml
!include .\\noivaciaAPP\src\model\ItemCasamento.puml
!include .\\noivaciaAPP\src\model\Model.puml
!include .\\noivaciaAPP\src\persistence\DatabaseConnection.puml
!include .\\noivaciaAPP\src\persistence\IDatabase.puml
!include .\\noivaciaAPP\src\persistence\IDatabaseImpl.puml
!include .\\noivaciaAPP\src\repository\ItemCasamentoRepository.puml
!include .\\noivaciaAPP\src\testes\CalendarioTeste.puml
!include .\\noivaciaAPP\src\testes\MainTeste.puml
!include .\\noivaciaAPP.Test\src\mapper\ItemCasamentoMapperTest.puml
!include .\\noivaciaAPP\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\noivaciaAPP\obj\Debug\net7.0\noivaciaAPP.AssemblyInfo.puml
!include .\\noivaciaAPP\obj\Debug\net7.0\noivaciaAPP.GlobalUsings.g.puml
!include .\\noivaciaAPP\obj\Debug\net7.0\noivaciaAPP.Program.puml
!include .\\noivaciaAPP\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\noivaciaAPP\obj\Debug\net8.0\noivaciaAPP.AssemblyInfo.puml
!include .\\noivaciaAPP\obj\Debug\net8.0\noivaciaAPP.GlobalUsings.g.puml
!include .\\noivaciaAPP\src\injection\repository\RepositoryInjection.puml
!include .\\noivaciaAPP\src\model\enum\TipoEspaco.puml
!include .\\noivaciaAPP\src\model\enum\TipoFesta.puml
!include .\\noivaciaAPP\src\model\enum\TipoItemFesta.puml
!include .\\noivaciaAPP.Test\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\noivaciaAPP.Test\obj\Debug\net8.0\noivaciaAPP.Test.AssemblyInfo.puml
!include .\\noivaciaAPP.Test\obj\Debug\net8.0\noivaciaAPP.Test.GlobalUsings.g.puml
@enduml
